USE DataWarehouse;
GO

/*
===============================================================================
DDL Script: Bronze Layer - Application Tables
===============================================================================
Script Purpose:
    Creates raw bronze tables for Home Credit application datasets.

Important Design Rules:
    - Bronze = raw landing layer
    - All columns stored as NVARCHAR
    - No datatype conversion
    - No business logic
    - No constraints / PK / FK
    - Includes audit column dwh_load_date
===============================================================================
*/

DROP TABLE IF EXISTS bronze.application_test;
DROP TABLE IF EXISTS bronze.application_train;
GO

/*
===============================================================================
application_train
===============================================================================
*/

CREATE TABLE bronze.application_train (

    SK_ID_CURR NVARCHAR(255),
    TARGET NVARCHAR(255),

    NAME_CONTRACT_TYPE NVARCHAR(255),
    CODE_GENDER NVARCHAR(255),

    FLAG_OWN_CAR NVARCHAR(255),
    FLAG_OWN_REALTY NVARCHAR(255),

    CNT_CHILDREN NVARCHAR(255),

    AMT_INCOME_TOTAL NVARCHAR(255),
    AMT_CREDIT NVARCHAR(255),
    AMT_ANNUITY NVARCHAR(255),
    AMT_GOODS_PRICE NVARCHAR(255),

    NAME_TYPE_SUITE NVARCHAR(255),
    NAME_INCOME_TYPE NVARCHAR(255),
    NAME_EDUCATION_TYPE NVARCHAR(255),
    NAME_FAMILY_STATUS NVARCHAR(255),
    NAME_HOUSING_TYPE NVARCHAR(255),

    REGION_POPULATION_RELATIVE NVARCHAR(255),

    DAYS_BIRTH NVARCHAR(255),
    DAYS_EMPLOYED NVARCHAR(255),
    DAYS_REGISTRATION NVARCHAR(255),
    DAYS_ID_PUBLISH NVARCHAR(255),

    OWN_CAR_AGE NVARCHAR(255),

    FLAG_MOBIL NVARCHAR(255),
    FLAG_EMP_PHONE NVARCHAR(255),
    FLAG_WORK_PHONE NVARCHAR(255),
    FLAG_CONT_MOBILE NVARCHAR(255),
    FLAG_PHONE NVARCHAR(255),
    FLAG_EMAIL NVARCHAR(255),

    OCCUPATION_TYPE NVARCHAR(255),

    CNT_FAM_MEMBERS NVARCHAR(255),

    REGION_RATING_CLIENT NVARCHAR(255),
    REGION_RATING_CLIENT_W_CITY NVARCHAR(255),

    WEEKDAY_APPR_PROCESS_START NVARCHAR(255),
    HOUR_APPR_PROCESS_START NVARCHAR(255),

    REG_REGION_NOT_LIVE_REGION NVARCHAR(255),
    REG_REGION_NOT_WORK_REGION NVARCHAR(255),
    LIVE_REGION_NOT_WORK_REGION NVARCHAR(255),

    REG_CITY_NOT_LIVE_CITY NVARCHAR(255),
    REG_CITY_NOT_WORK_CITY NVARCHAR(255),
    LIVE_CITY_NOT_WORK_CITY NVARCHAR(255),

    ORGANIZATION_TYPE NVARCHAR(255),

    EXT_SOURCE_1 NVARCHAR(255),
    EXT_SOURCE_2 NVARCHAR(255),
    EXT_SOURCE_3 NVARCHAR(255),

    APARTMENTS_AVG NVARCHAR(255),
    BASEMENTAREA_AVG NVARCHAR(255),
    YEARS_BEGINEXPLUATATION_AVG NVARCHAR(255),
    YEARS_BUILD_AVG NVARCHAR(255),
    COMMONAREA_AVG NVARCHAR(255),
    ELEVATORS_AVG NVARCHAR(255),
    ENTRANCES_AVG NVARCHAR(255),
    FLOORSMAX_AVG NVARCHAR(255),
    FLOORSMIN_AVG NVARCHAR(255),
    LANDAREA_AVG NVARCHAR(255),
    LIVINGAPARTMENTS_AVG NVARCHAR(255),
    LIVINGAREA_AVG NVARCHAR(255),
    NONLIVINGAPARTMENTS_AVG NVARCHAR(255),
    NONLIVINGAREA_AVG NVARCHAR(255),

    APARTMENTS_MODE NVARCHAR(255),
    BASEMENTAREA_MODE NVARCHAR(255),
    YEARS_BEGINEXPLUATATION_MODE NVARCHAR(255),
    YEARS_BUILD_MODE NVARCHAR(255),
    COMMONAREA_MODE NVARCHAR(255),
    ELEVATORS_MODE NVARCHAR(255),
    ENTRANCES_MODE NVARCHAR(255),
    FLOORSMAX_MODE NVARCHAR(255),
    FLOORSMIN_MODE NVARCHAR(255),
    LANDAREA_MODE NVARCHAR(255),
    LIVINGAPARTMENTS_MODE NVARCHAR(255),
    LIVINGAREA_MODE NVARCHAR(255),
    NONLIVINGAPARTMENTS_MODE NVARCHAR(255),
    NONLIVINGAREA_MODE NVARCHAR(255),

    APARTMENTS_MEDI NVARCHAR(255),
    BASEMENTAREA_MEDI NVARCHAR(255),
    YEARS_BEGINEXPLUATATION_MEDI NVARCHAR(255),
    YEARS_BUILD_MEDI NVARCHAR(255),
    COMMONAREA_MEDI NVARCHAR(255),
    ELEVATORS_MEDI NVARCHAR(255),
    ENTRANCES_MEDI NVARCHAR(255),
    FLOORSMAX_MEDI NVARCHAR(255),
    FLOORSMIN_MEDI NVARCHAR(255),
    LANDAREA_MEDI NVARCHAR(255),
    LIVINGAPARTMENTS_MEDI NVARCHAR(255),
    LIVINGAREA_MEDI NVARCHAR(255),
    NONLIVINGAPARTMENTS_MEDI NVARCHAR(255),
    NONLIVINGAREA_MEDI NVARCHAR(255),

    FONDKAPREMONT_MODE NVARCHAR(255),
    HOUSETYPE_MODE NVARCHAR(255),

    TOTALAREA_MODE NVARCHAR(255),

    WALLSMATERIAL_MODE NVARCHAR(255),
    EMERGENCYSTATE_MODE NVARCHAR(255),

    OBS_30_CNT_SOCIAL_CIRCLE NVARCHAR(255),
    DEF_30_CNT_SOCIAL_CIRCLE NVARCHAR(255),

    OBS_60_CNT_SOCIAL_CIRCLE NVARCHAR(255),
    DEF_60_CNT_SOCIAL_CIRCLE NVARCHAR(255),

    DAYS_LAST_PHONE_CHANGE NVARCHAR(255),

    FLAG_DOCUMENT_2 NVARCHAR(255),
    FLAG_DOCUMENT_3 NVARCHAR(255),
    FLAG_DOCUMENT_4 NVARCHAR(255),
    FLAG_DOCUMENT_5 NVARCHAR(255),
    FLAG_DOCUMENT_6 NVARCHAR(255),
    FLAG_DOCUMENT_7 NVARCHAR(255),
    FLAG_DOCUMENT_8 NVARCHAR(255),
    FLAG_DOCUMENT_9 NVARCHAR(255),
    FLAG_DOCUMENT_10 NVARCHAR(255),
    FLAG_DOCUMENT_11 NVARCHAR(255),
    FLAG_DOCUMENT_12 NVARCHAR(255),
    FLAG_DOCUMENT_13 NVARCHAR(255),
    FLAG_DOCUMENT_14 NVARCHAR(255),
    FLAG_DOCUMENT_15 NVARCHAR(255),
    FLAG_DOCUMENT_16 NVARCHAR(255),
    FLAG_DOCUMENT_17 NVARCHAR(255),
    FLAG_DOCUMENT_18 NVARCHAR(255),
    FLAG_DOCUMENT_19 NVARCHAR(255),
    FLAG_DOCUMENT_20 NVARCHAR(255),
    FLAG_DOCUMENT_21 NVARCHAR(255),

    AMT_REQ_CREDIT_BUREAU_HOUR NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_DAY NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_WEEK NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_MON NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_QRT NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_YEAR NVARCHAR(255),

    dwh_load_date DATETIME2 DEFAULT GETDATE()

);
GO

/*
===============================================================================
application_test
===============================================================================
*/

CREATE TABLE bronze.application_test (

    SK_ID_CURR NVARCHAR(255),

    NAME_CONTRACT_TYPE NVARCHAR(255),
    CODE_GENDER NVARCHAR(255),

    FLAG_OWN_CAR NVARCHAR(255),
    FLAG_OWN_REALTY NVARCHAR(255),

    CNT_CHILDREN NVARCHAR(255),

    AMT_INCOME_TOTAL NVARCHAR(255),
    AMT_CREDIT NVARCHAR(255),
    AMT_ANNUITY NVARCHAR(255),
    AMT_GOODS_PRICE NVARCHAR(255),

    NAME_TYPE_SUITE NVARCHAR(255),
    NAME_INCOME_TYPE NVARCHAR(255),
    NAME_EDUCATION_TYPE NVARCHAR(255),
    NAME_FAMILY_STATUS NVARCHAR(255),
    NAME_HOUSING_TYPE NVARCHAR(255),

    REGION_POPULATION_RELATIVE NVARCHAR(255),

    DAYS_BIRTH NVARCHAR(255),
    DAYS_EMPLOYED NVARCHAR(255),
    DAYS_REGISTRATION NVARCHAR(255),
    DAYS_ID_PUBLISH NVARCHAR(255),

    OWN_CAR_AGE NVARCHAR(255),

    FLAG_MOBIL NVARCHAR(255),
    FLAG_EMP_PHONE NVARCHAR(255),
    FLAG_WORK_PHONE NVARCHAR(255),
    FLAG_CONT_MOBILE NVARCHAR(255),
    FLAG_PHONE NVARCHAR(255),
    FLAG_EMAIL NVARCHAR(255),

    OCCUPATION_TYPE NVARCHAR(255),

    CNT_FAM_MEMBERS NVARCHAR(255),

    REGION_RATING_CLIENT NVARCHAR(255),
    REGION_RATING_CLIENT_W_CITY NVARCHAR(255),

    WEEKDAY_APPR_PROCESS_START NVARCHAR(255),
    HOUR_APPR_PROCESS_START NVARCHAR(255),

    REG_REGION_NOT_LIVE_REGION NVARCHAR(255),
    REG_REGION_NOT_WORK_REGION NVARCHAR(255),
    LIVE_REGION_NOT_WORK_REGION NVARCHAR(255),

    REG_CITY_NOT_LIVE_CITY NVARCHAR(255),
    REG_CITY_NOT_WORK_CITY NVARCHAR(255),
    LIVE_CITY_NOT_WORK_CITY NVARCHAR(255),

    ORGANIZATION_TYPE NVARCHAR(255),

    EXT_SOURCE_1 NVARCHAR(255),
    EXT_SOURCE_2 NVARCHAR(255),
    EXT_SOURCE_3 NVARCHAR(255),

    APARTMENTS_AVG NVARCHAR(255),
    BASEMENTAREA_AVG NVARCHAR(255),
    YEARS_BEGINEXPLUATATION_AVG NVARCHAR(255),
    YEARS_BUILD_AVG NVARCHAR(255),
    COMMONAREA_AVG NVARCHAR(255),
    ELEVATORS_AVG NVARCHAR(255),
    ENTRANCES_AVG NVARCHAR(255),
    FLOORSMAX_AVG NVARCHAR(255),
    FLOORSMIN_AVG NVARCHAR(255),
    LANDAREA_AVG NVARCHAR(255),
    LIVINGAPARTMENTS_AVG NVARCHAR(255),
    LIVINGAREA_AVG NVARCHAR(255),
    NONLIVINGAPARTMENTS_AVG NVARCHAR(255),
    NONLIVINGAREA_AVG NVARCHAR(255),

    APARTMENTS_MODE NVARCHAR(255),
    BASEMENTAREA_MODE NVARCHAR(255),
    YEARS_BEGINEXPLUATATION_MODE NVARCHAR(255),
    YEARS_BUILD_MODE NVARCHAR(255),
    COMMONAREA_MODE NVARCHAR(255),
    ELEVATORS_MODE NVARCHAR(255),
    ENTRANCES_MODE NVARCHAR(255),
    FLOORSMAX_MODE NVARCHAR(255),
    FLOORSMIN_MODE NVARCHAR(255),
    LANDAREA_MODE NVARCHAR(255),
    LIVINGAPARTMENTS_MODE NVARCHAR(255),
    LIVINGAREA_MODE NVARCHAR(255),
    NONLIVINGAPARTMENTS_MODE NVARCHAR(255),
    NONLIVINGAREA_MODE NVARCHAR(255),

    APARTMENTS_MEDI NVARCHAR(255),
    BASEMENTAREA_MEDI NVARCHAR(255),
    YEARS_BEGINEXPLUATATION_MEDI NVARCHAR(255),
    YEARS_BUILD_MEDI NVARCHAR(255),
    COMMONAREA_MEDI NVARCHAR(255),
    ELEVATORS_MEDI NVARCHAR(255),
    ENTRANCES_MEDI NVARCHAR(255),
    FLOORSMAX_MEDI NVARCHAR(255),
    FLOORSMIN_MEDI NVARCHAR(255),
    LANDAREA_MEDI NVARCHAR(255),
    LIVINGAPARTMENTS_MEDI NVARCHAR(255),
    LIVINGAREA_MEDI NVARCHAR(255),
    NONLIVINGAPARTMENTS_MEDI NVARCHAR(255),
    NONLIVINGAREA_MEDI NVARCHAR(255),

    FONDKAPREMONT_MODE NVARCHAR(255),
    HOUSETYPE_MODE NVARCHAR(255),

    TOTALAREA_MODE NVARCHAR(255),

    WALLSMATERIAL_MODE NVARCHAR(255),
    EMERGENCYSTATE_MODE NVARCHAR(255),

    OBS_30_CNT_SOCIAL_CIRCLE NVARCHAR(255),
    DEF_30_CNT_SOCIAL_CIRCLE NVARCHAR(255),

    OBS_60_CNT_SOCIAL_CIRCLE NVARCHAR(255),
    DEF_60_CNT_SOCIAL_CIRCLE NVARCHAR(255),

    DAYS_LAST_PHONE_CHANGE NVARCHAR(255),

    FLAG_DOCUMENT_2 NVARCHAR(255),
    FLAG_DOCUMENT_3 NVARCHAR(255),
    FLAG_DOCUMENT_4 NVARCHAR(255),
    FLAG_DOCUMENT_5 NVARCHAR(255),
    FLAG_DOCUMENT_6 NVARCHAR(255),
    FLAG_DOCUMENT_7 NVARCHAR(255),
    FLAG_DOCUMENT_8 NVARCHAR(255),
    FLAG_DOCUMENT_9 NVARCHAR(255),
    FLAG_DOCUMENT_10 NVARCHAR(255),
    FLAG_DOCUMENT_11 NVARCHAR(255),
    FLAG_DOCUMENT_12 NVARCHAR(255),
    FLAG_DOCUMENT_13 NVARCHAR(255),
    FLAG_DOCUMENT_14 NVARCHAR(255),
    FLAG_DOCUMENT_15 NVARCHAR(255),
    FLAG_DOCUMENT_16 NVARCHAR(255),
    FLAG_DOCUMENT_17 NVARCHAR(255),
    FLAG_DOCUMENT_18 NVARCHAR(255),
    FLAG_DOCUMENT_19 NVARCHAR(255),
    FLAG_DOCUMENT_20 NVARCHAR(255),
    FLAG_DOCUMENT_21 NVARCHAR(255),

    AMT_REQ_CREDIT_BUREAU_HOUR NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_DAY NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_WEEK NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_MON NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_QRT NVARCHAR(255),
    AMT_REQ_CREDIT_BUREAU_YEAR NVARCHAR(255),

    dwh_load_date DATETIME2 DEFAULT GETDATE()

);
GO